### ISSUE TITLE
attribution

### ISSUE THREAD

**Issue by carolineartz** [LinkStackOrg/Bongo-Cat#1]
Hi -- could you please provide attribution to my original work? https://codepen.io/carolineartz/details/qBOEzQa The [linked work](https://codepen.io/MrS4nty/pen/MWVdjKG) is a copy of it.

**Comment by JulianPrieber** [comment]
Certainly. We regret that we did not properly credit your original work. We'll make sure to give your work the credit it deserves and to properly credit you for all uses of it.

**Comment by JulianPrieber** [comment]
@MagicLike

**Comment by carolineartz** [comment]
Thanks much!
